---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Gateway
      name: http
      namespace: kube-system
    patch: |
      - op: add
        path: /spec/listeners/0/hostname
        value: *.localhost
