---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Gateway
      name: external-http-gateway
      namespace: istio-ingress
    patch: |
      - op: add
        path: /spec/listeners/0/hostname
        value: "*.localhost"
