apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  generation: 1
  name: zii-gateway
  namespace: commands
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - api-dev.ziichat.dev
      port:
        name: ziichat-media-http
        number: 80
        protocol: HTTP
    - hosts:
        - filestore-dev.ziichat.dev
      port:
        name: ziichat-filestore-http
        number: 80
        protocol: HTTP
    - hosts:
        - dev.zii.chat
      port:
        name: zii.chat-shortlink-http
        number: 80
        protocol: HTTP