---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: http
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
